#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Author: Ina Robinson
# Course: Open Source Software
# -------------------------------
# Section 1: User Input
# -------------------------------
echo "Answer the following questions to generate your manifesto:"
echo ""
read -p "1. Name one open-source tool you use every day: " TOOL
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM
read -p "3. Name one thing you would build and share freely: " BUILD
# -------------------------------
# Section 2: Variables
# -------------------------------
DATE=$(date '+%d %B %Y')
OUTPUT="manifesto_$(whoami).txt"
# -------------------------------
# Section 3: Generate Manifesto
# -------------------------------
echo "----------------------------------------" > $OUTPUT
echo " Open Source Manifesto" >> $OUTPUT
echo "----------------------------------------" >> $OUTPUT
echo "Date: $DATE" >> $OUTPUT
echo "" >> $OUTPUT
echo "I use $TOOL regularly, which represents the power of open-source software." >> $OUTPUT
echo "For me, freedom means $FREEDOM, and I believe in sharing knowledge with others." >> $OUTPUT
echo "I would like to build $BUILD and make it available for everyone to use." >> $OUTPUT
echo "This reflects my belief in collaboration, transparency, and innovation." >> $OUTPUT
echo "" >> $OUTPUT
echo "Generated by: $(whoami)" >> $OUTPUT
# -------------------------------
# Section 4: Output Display
# -------------------------------
echo ""
echo "Manifesto successfully created!"
echo "Saved as: $OUTPUT"
echo ""
echo "----- Your Manifesto -----"
cat $OUTPUT
